services:
  chainlink-automation-poller:
    build: .
    container_name: chainlink-automation-poller
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    entrypoint: ["sh", "-c", "./set_env.sh && node --no-deprecation app.js"]